# Generated by Django 5.2 on 2025-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mac', models.CharField(max_length=17)),
                ('ap_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('gateway_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('ssid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vlan_id', models.CharField(blank=True, max_length=10, null=True)),
                ('radio_id', models.CharField(blank=True, max_length=10, null=True)),
                ('site_name', models.CharField(max_length=100)),
                ('redirect_url', models.URLField()),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
